<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="xunit" />
		<PackageReference Include="xunit.runner.visualstudio" />
		<PackageReference Include="Moq" />
		<PackageReference Include="FluentAssertions" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Api.GRRInnovations.Memorix.Application\Api.GRRInnovations.Memorix.Application.csproj" />
		<ProjectReference Include="..\..\Api.GRRInnovations.Memorix.Domain\Api.GRRInnovations.Memorix.Domain.csproj" />
		<ProjectReference Include="..\..\Api.GRRInnovations.Memorix.Infrastructure\Api.GRRInnovations.Memorix.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Controllers\" />
	  <Folder Include="Infrastructure\" />
	  <Folder Include="Fixtures\" />
	  <Folder Include="Services\" />
	</ItemGroup>

</Project>
